### ISSUE TITLE
Is there anyway to build this example in visual studio 2015?

### ISSUE THREAD

**Issue by blackapple1202** [idmillington/cyclone-physics#44]
Hello guys, I have two questions.
First of all, is there anyway to build this example in visual studio 2015? I downloaded the example and find build folder and executed sln files. However there is only vs2005 and vs2010 so I'm curious if there is a vs2015 version for this example.
Secondly, if there is no way to compile and build in vs2015, I'm going to uninstall vs2015 and install vs2010. I would like to know detailed manual for compiling / building examples in vs2010. (Like setting linking or something)
Give me a hand guys!

**Comment by xiangwei71** [comment]
I create a new project with vs2017 and move code from here to there . Finally I success XD

**Comment by blackapple1202** [comment]
Thx man, I really appreciate XD

2017-08-13 21:26 GMT+09:00 xiangwei71 <notifications@github.com>:

**Comment by zinwalin** [comment]
> I create a new project with vs2017 and move code from here to there . Finally I success XD

can you upload to github?  appreciated!

**Comment by xiangwei71** [comment]
> > I create a new project with vs2017 and move code from here to there . Finally I success XD
> 
> can you upload to github? appreciated!

I'd love to . But I already do not know how I could do it. ><
